### PR TITLE
Show github annotation on specific errors.

### PR DESCRIPTION
**Pull request by Hoverbear**
Show a Github Actions error annotation on UNAUTHORIZED responses such that users may see experience an elevated error experience in this expected error case.

### CODE REVIEW

**Comment by Hoverbear** [comment]
Heck let me add the conflict too

**Review by cole-h — APPROVED** [review]
LGTM, but I do wonder if we could put these in some other place so that we don't forget if we ever add more (maybe it could be part of the `should_suggest_issue` function in `error.rs`...?)

**Comment by Hoverbear** [comment]
@cole-h I was looking around for a good way to do this but didn't immediately think of one. Now that I've tested this works I may actually have an idea...

**Review by cole-h — APPROVED** [review]
Noice!

**Pull request merged**
